MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.0
  SWIN:
    IMG_SIZE: (1472, 960)
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: (7,7)
    PATCH_SIZE: (4,4)